2025-03-17 13:54:49,907 INFO    MainThread:115651 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-17 13:54:49,912 INFO    MainThread:115651 [wandb_setup.py:_flush():67] Configure stats pid to 115651
2025-03-17 13:54:49,912 INFO    MainThread:115651 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-17 13:54:49,912 INFO    MainThread:115651 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-17 13:54:49,912 INFO    MainThread:115651 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-17 13:54:49,912 INFO    MainThread:115651 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250317_135449-oyn0vm6u/logs/debug.log
2025-03-17 13:54:49,912 INFO    MainThread:115651 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250317_135449-oyn0vm6u/logs/debug-internal.log
2025-03-17 13:54:49,912 INFO    MainThread:115651 [wandb_init.py:init():761] calling init triggers
2025-03-17 13:54:49,912 INFO    MainThread:115651 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'wandb_project': 'myprojectname', 'wandb_entity': 'myname', 'dataset': 'fashion_mnist', 'epochs': 10, 'batch_size': 64, 'loss': 'cross_entropy', 'optimizer': 'adam', 'learning_rate': 0.001, 'momentum': 0.5, 'beta': 0.5, 'beta1': 0.9, 'beta2': 0.999, 'epsilon': 1e-06, 'weight_decay': 0.0005, 'weight_init': 'Xavier', 'num_layers': 4, 'hidden_size': 128, 'activation': 'ReLU', '_wandb': {}}
2025-03-17 13:54:49,912 INFO    MainThread:115651 [wandb_init.py:init():784] starting backend
2025-03-17 13:54:49,912 INFO    MainThread:115651 [wandb_init.py:init():788] sending inform_init request
2025-03-17 13:54:49,925 INFO    MainThread:115651 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-17 13:54:49,929 INFO    MainThread:115651 [wandb_init.py:init():803] backend started and connected
2025-03-17 13:54:49,931 INFO    MainThread:115651 [wandb_init.py:init():896] updated telemetry
2025-03-17 13:54:49,943 INFO    MainThread:115651 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-17 13:54:50,418 ERROR   MainThread:115651 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 968, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-03-17 13:54:50,439 WARNING MsgRouterThr:115651 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-17 13:54:50,440 INFO    MsgRouterThr:115651 [mailbox.py:close():115] Closing mailbox, abandoning 0 handles.
